const express = require('express')
const route = express.Router()
const control = require('../controller/userprofile.js')
route.get('/', control.user)
route.get('/status', control.userStatus)
route.get('/profile', control.userdata)
route.get('/carrer', control.getuserCarrer)
route.put('/profileUpdate', control.profileUpdate)
route.put('/carrerUpdate', control.carrerUpdate)
route.delete('/', control.deleteAccount)
module.exports = route